# Generated by Django 3.1.6 on 2021-02-13 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angle',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
